fabien_crassat_curriculum_vitae:
  path_to_cv:       "%kernel.root_dir%/resources/curriculumvitae"
  custo_default_cv: "fabien"
  template:         "@FabienCrassatCurriculumVitae/CurriculumVitae/OryzoneBoilerplate.html.twig"

twig:
  globals:
    bp_analytics_id: '%env(google_analytics_id)%'
    bp_analytics_domain: '%env(google_analytics_domain)%'
