# app/config/config.yml
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.yml}

framework:
    secret:          %secret%
    trusted_proxies: ~
    # default_locale:  %locale%

    # esi configuration
    #esi:             ~

    # translator configuration
    translator: ~
        # enabled:     true
        # fallback:    %locale%

    # router configuration
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        # set to true to throw an exception when a parameter does not match the requirements
        # set to false to disable exceptions when a parameter does not match the requirements (and return null instead)
        # set to null to disable parameter checks against requirements
        # 'true' is the preferred configuration in development mode, while 'false' or 'null' might be preferred in production
        strict_requirements: ~

    # form configuration
    form:            ~
    csrf_protection: ~

    # validation configuration
    validation:      { enable_annotations: true }

    # templating configuration
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme

    # session configuration
    session:         ~

    # fragments configuration
    fragments:       ~

# Assetic Configuration
assetic:
    bundles:        ["OryzoneBoilerplateBundle"]

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        bp_language: %locale%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# Services
services:
    kernel.listener.LocaleListener:
        class: Nbs\Bundle\CVBundle\Listener\LocaleListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

# MRemi Contact Configuration
mremi_contact:
    store_data:            false
    contact_class:         Mremi\ContactBundle\Model\Contact

    form:
        type:              mremi_contact
        name:              contact_form
        validation_groups: [Default]
        subject_provider:  mremi_contact.subject_provider.noop
        captcha_disabled:  false
        captcha_type:      genemu_captcha

    email:
        mailer:            mremi_contact.mailer.twig_swift
        recipient_address: webmaster@crassat.com
        template:          MremiContactBundle:Contact:email.txt.twig
