imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    translator: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ["OryzoneBoilerplateBundle", "FabienCrassatCurriculumVitaeBundle"]
    #Use the following link to avoid the is_dir(): open_basedir restriction in effect
    java:           "%kernel.root_dir%/../../../bin/java"
    node:           "%kernel.root_dir%/../../../bin/node"
    ruby:           "%kernel.root_dir%/../../../bin/ruby"
    sass:           "%kernel.root_dir%/../../../bin/sass"
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        #yui_js:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        uglifyjs2:
            bin: "%path_to_uglifyjs2%"
        uglifycss:
            bin: "%path_to_uglifycss%"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FabienCrassat Configuration
fabien_crassat_curriculum_vitae:
    path_to_cv:       "%kernel.root_dir%/../src/Nbs/Bundle/CVBundle/Resources/curriculumvitae"
    custo_default_cv: "fabien"
    template:         "NbsCVBundle:Default:index.html.twig"

# Mremi Contact Configuration
mremi_contact:
    store_data:            false
    contact_class:         Mremi\ContactBundle\Model\Contact

    form:
        type:              mremi_contact
        name:              contact_form
        validation_groups: [Default]
        subject_provider:  mremi_contact.subject_provider.noop
        captcha_disabled:  false
        captcha_type:      genemu_captcha

    email:
        mailer:            mremi_contact.mailer.twig_swift
        recipient_address: webmaster@crassat.com
        template:          MremiContactBundle:Contact:email.txt.twig

# knp_snappy Configuration
knp_snappy:
    pdf:
        enabled:    true
        binary:     %kernel.root_dir%/../bin/wkhtmltopdf
        options:    []
    image:
        enabled:    false
        binary:     /usr/local/bin/wkhtmltoimage
        options:    []
