nbs_cv_homepage:
    pattern:    /
    defaults:
        _controller:    FrameworkBundle:Redirect:redirect
        route:          nbs_cv_local
        permanent:      true

nbs_cv_local:
    path:       /fabien/{_locale}
    defaults:   { _controller: NbsCVBundle:Default:index, _locale: en }
    requirements:
        _locale: en|fr