nbs_cv_homepage:
    pattern:    /
    defaults:
        _controller:    FrameworkBundle:Redirect:redirect
        route:          nbs_cv_local
        permanent:      true

nbs_cv_fabien:
    path:    /fabien
    defaults:
        _controller:    FrameworkBundle:Redirect:redirect
        route:          nbs_cv_local
        permanent:      true

nbs_cv_fabien_locale:
    path:    /fabien/{_locale}
    defaults:
        _controller:    FrameworkBundle:Redirect:redirect
        route:          nbs_cv_local
        permanent:      true

nbs_cv_local:
    path:       /cv/{cvxmlfile}/{_locale}
    defaults:
        _controller:    NbsCVBundle:Default:index
        _locale:        en
        cvxmlfile:      fabien
    requirements:
        _locale:        en|fr
        cvxmlfile:      fabien|test