parameters:
#    nbs_cv.example.class: Nbs\Bundle\CVBundle\Example

services:
#    nbs_cv.example:
#        class: %nbs_cv.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
